version: '3'

services:
  # MinIO - S3 Compatible Object Storage (Storage Layer)
  minio:
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # Create initial buckets in MinIO
  mc:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc config host add minio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb minio/raw-zone;
      /usr/bin/mc mb minio/trusted-zone;
      /usr/bin/mc mb minio/refined-zone;
      /usr/bin/mc mb minio/consumption-zone;
      exit 0;
      "

  # Mariadb for Hive Metastore
  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: hive
      MYSQL_PASSWORD: hive
      MYSQL_DATABASE: metastore_db
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init/mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  # Hive Metastore - Metadata Management
  hive-metastore:
    image: apache/hive:3.1.3
    container_name: hive-metastore
    depends_on:
      - mariadb
    environment:
      DB_DRIVER: mysql
      DB_HOST: mariadb
      DB_NAME: metastore_db
      DB_USER: hive
      DB_PASSWORD: hive
      METASTORE_JDBC_URL: jdbc:mysql://mariadb:3306/metastore_db
      HADOOP_HOME: /opt/hadoop
    ports:
      - "9083:9083"
    volumes:
      - ./config/hive/hive-site.xml:/opt/hive/conf/hive-site.xml
      - ./data:/data

  # Trino (formerly PrestoSQL) - SQL Query Engine
  trino:
    image: trinodb/trino:403
    container_name: trino
    ports:
      - "8080:8080"
    volumes:
      - ./config/trino/:/etc/trino/
    depends_on:
      - hive-metastore
      - minio

  # Python client for interacting with Data Lake
  python-client:
    image: python:3.9-slim
    container_name: python-client
    volumes:
      - ./scripts:/scripts
      - ./data:/data
    working_dir: /scripts
    command: >
      bash -c "pip install minio pandas pyarrow requests trino && tail -f /dev/null"
    depends_on:
      - trino
      - minio

volumes:
  minio_data:
  mariadb_data:
